# # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
# Sorting Algorithms
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # #

# Which compile t use
CC = gcc

# compiler flags:
# -I	Include path
# -O	slow compile but fast execution
# -g	adds debugging information to the executable file
# -Wall turns on most, but not all, compiler warnings
FLAGS = -I../. -O -g -Wall

# Program name
BUBBLESORT = BubbleSort
MAIN = main

# Source files

default:
	$(CC) $(CFLAGS) -o $(MAIN) *.c

clean:
	-rm -f $(MAIN)
